# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0002_auto_20160120_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='Bogota', max_length=100),
        ),
    ]
