# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0003_person_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.AddField(
            model_name='person',
            name='town',
            field=models.CharField(default='Bogota', max_length=100),
            preserve_default=False,
        ),
    ]
