# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0005_auto_20160120_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='ubica',
        ),
    ]
