# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0006_auto_20160120_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
