# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0007_person_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='ubica',
            new_name='city',
        ),
    ]
