# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0008_auto_20160120_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_background', models.CharField(max_length=100)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cover.Person')),
            ],
        ),
    ]
