# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0010_auto_20160126_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cellphone', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
